using Pertamina.IRIS.Models.Base;
using System;
using System.Collections.Generic;
using System.Text;

namespace Pertamina.IRIS.Services.Interfaces
{
    public interface IDropDownListService
    {
        List<Select2BaseModel> DdlHsh(string query);
        List<Select2BaseModel> DdlEntitasPertamina(string query);
        List<Select2BaseModel> DdlEntitasPertaminaGrid(string query);
        List<Select2BaseModel> DdlFungsi(string query);
        List<Select2BaseModel> DdlStreamBusiness(string query);
        List<Select2BaseModel> DdlOpportunityEntitasPertamina(string query);
        List<Select2BaseModel> DdlOpportunityPic(string query);
        List<Select2BaseModel> DdlOpportunityKesiapanProyek(string query);
        List<Select2BaseModel> DdlOpportunityNegara(string query);
        List<Select2BaseModel> DdlOpportunityTargetMitra(string query);
        List<Select2BaseModel> DdlInterest(string query);
        List<Select2BaseModel> DdlInitiativeStatus(string query);
        List<Select2BaseModel> DdlInitiativeTypes(string query);
        List<Select2BaseModel> DdlInitiativeStages(string query);
        List<Select2BaseModel> DdlKawasanMitra(string query);
        List<Select2BaseModel> DdlNegaraMitra(string query);
        List<Select2BaseModel> DdlNegaraMitraOnlyNegara(string query);
        List<Select2BaseModel> DdlNegaraMitraWithoutKawasan(string query);
        List<Select2BaseModel> DdlPic(string query);
        List<Select2BaseModel> DdlPicLevel(string query);
        List<Select2BaseModel> DdlProvinsiIndonesia(string query);
        List<Select2BaseModel> DdlHubHead(string query);
        List<Select2BaseModel> DdlHub(string query);
        List<Select2BaseModel> DdlRelatedAgreement(string query);
        List<Select2BaseModel> DdlHshEntitasPertamina(string query);
        List<Select2BaseModel> DdlStatusBerlaku(string query);
        List<Select2BaseModel> DdlTrafficLight(string query);
        List<Select2BaseModel> DdlInitiativeForm(string query);
        List<Select2BaseModel> DdlNamaProyek(string query, string value);
        List<Select2BaseModel> DdlNamaProyekInitiative(string query, string value);
        List<Select2BaseModel> DdlStatusDiscussion(string query);
        List<Select2BaseModel> DdlJenisPerjanjian(string query);
        List<Select2BaseModel> DdlAgreementForm(string query);
        Select2BaseModel GetDdlEntitasPertamina(Guid guid);
        Select2BaseModel GetDdlHub(Guid guid);
        Select2BaseModel GetDdlFungsi(Guid guid);
        Select2BaseModel GetDdlPicLevel(Guid guid);
        Select2BaseModel GetDdlPicFungsi(Guid guid);
        Select2BaseModel GetDdlHsh(Guid guid);
        Select2BaseModel GetDdlInterest(Guid guid);
        Select2BaseModel GetDdlInitiativeStatus(Guid guid);
        Select2BaseModel GetDdlInitiativeTypes(Guid guid);
        Select2BaseModel GetDdlInitiativeStages(Guid guid);
        Select2BaseModel GetDdlKawasanMitra(Guid guid);
        Select2BaseModel GetDdlNegaraMitra(Guid guid);
        Select2BaseModel GetDdlNegaraMitraOnlyNegara(Guid guid);
        Select2BaseModel GetDdlOpportunity(Guid guid);
        Select2BaseModel GetDdlStreamBusiness(Guid guid);
        Select2BaseModel GetDdlHshEntitasPertamina(Guid guid);
        List<Select2BaseModel> GetDdlOpportunityStreamBusiness(Guid guid);
        List<Select2BaseModel> GetDdlInitiativeEntitasPertamina(Guid guid);
        List<Select2BaseModel> GetDdlInitiativePicFungsi(Guid guid);
        List<Select2BaseModel> GetDdlInitiativeStreamBusiness(Guid guid);
        List<Select2BaseModel> GetDdlOpportunityEntitasPertamina(Guid guid);
        List<Select2BaseModel> GetDdlOpportunityPicFungsi(Guid guid);
        List<Select2BaseModel> GetDdlOpportunityKesiapanProyek(Guid guid);
        List<Select2BaseModel> GetDdlOpportunityNegara(Guid guid);
        List<Select2BaseModel> GetDdlOpportunityTargetMitra(Guid guid);
        Select2BaseModel GetDdlRelatedAgreement(Guid guid);
        List<Select2BaseModel> GetDdlInitiativeNegara(Guid guid);
        List<Select2BaseModel> DdlFaktorKendala(string query);
        List<Select2BaseModel> DdlKlasifikasiKendala(string query);
        List<Select2BaseModel> DdlKeterlibatanLembaga(string query);
        List<Select2BaseModel> DdlYear(string query);
        List<Select2BaseModel> GetDdlAgreementStreamBusiness(Guid guid);
        List<Select2BaseModel> GetDdlAgreementPicFungsi(Guid guid);
        List<Select2BaseModel> GetDdlAgreementEntitasPertamina(Guid guid);
        List<Select2BaseModel> GetDdlAgreementNegara(Guid guid);
        List<Select2BaseModel> GetDdlAgreementJenisPerjanjian(Guid guid);
        List<Select2BaseModel> GetDdlAgreementStatusDiscussion(Guid guid);
        List<Select2BaseModel> GetDdlAgreementFaktorKendala(Guid guid);
        List<Select2BaseModel> GetDdlAgreementTrafficLight(Guid guid);
        List<Select2BaseModel> GetDdlAgreementKlasifikasiKendala(Guid guid);
        List<Select2BaseModel> GetDdlAgreementKeterlibatanLembaga(Guid guid);
        List<Select2BaseModel> GetDdlAgreementRelatedAgreement(Guid guid);
        List<Select2BaseModel> DdlTypeOfStudy(string query);
        List<Select2BaseModel> DdlConfidentiality(string query);
        List<Select2BaseModel> DdlOwnerEntity(string query);
        List<Select2BaseModel> DdlExistingFootprintsSortingHighPriority(string query);
        List<Select2BaseModel> DdlSignedAgreementSortingHighPriority(string query);
        List<Select2BaseModel> GetDdlInitiativeKeterlibatanLembaga(Guid guid);
    }
}
